-- Fin News schema bootstrap for Supabase SQL Editor
-- Generated by merging Prisma migrations into one idempotent-ish script.
-- Safe for first-time setup; re-running should mostly no-op.

BEGIN;

DO $$
BEGIN
  CREATE TYPE "ReportStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE "JobStatus" AS ENUM ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE "FeedbackReaction" AS ENUM ('LIKE', 'UNLIKE');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "NewsSource" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "feedUrl" TEXT NOT NULL,
  "sourceType" TEXT NOT NULL,
  "weight" DOUBLE PRECISION NOT NULL DEFAULT 1,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "NewsSource_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "RawNewsItem" (
  "id" TEXT NOT NULL,
  "sourceId" TEXT NOT NULL,
  "externalId" TEXT,
  "title" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "language" TEXT,
  "publishedAt" TIMESTAMP(3),
  "summary" TEXT,
  "content" TEXT,
  "importanceHint" DOUBLE PRECISION,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RawNewsItem_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "NewsEvent" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "summary" TEXT NOT NULL,
  "sentiment" TEXT,
  "importanceScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "sectors" TEXT[] NOT NULL,
  "tickers" TEXT[] NOT NULL,
  "marketDate" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "NewsEvent_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "NewsEventSource" (
  "id" TEXT NOT NULL,
  "eventId" TEXT NOT NULL,
  "rawNewsItemId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "NewsEventSource_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "DailyReport" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "marketDate" TIMESTAMP(3) NOT NULL,
  "title" TEXT NOT NULL,
  "summary" TEXT NOT NULL,
  "contentZhEn" TEXT NOT NULL,
  "sentimentSummary" TEXT,
  "sectorView" TEXT,
  "tradingView" TEXT,
  "riskWarning" TEXT NOT NULL,
  "disclaimer" TEXT NOT NULL,
  "status" "ReportStatus" NOT NULL DEFAULT 'DRAFT',
  "publishedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "DailyReport_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "DailyReportEvent" (
  "id" TEXT NOT NULL,
  "reportId" TEXT NOT NULL,
  "eventId" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL,
  CONSTRAINT "DailyReportEvent_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "StockFocus" (
  "id" TEXT NOT NULL,
  "reportId" TEXT NOT NULL,
  "symbol" TEXT NOT NULL,
  "company" TEXT,
  "thesis" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "StockFocus_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "AiProviderConfig" (
  "id" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "baseUrl" TEXT NOT NULL,
  "model" TEXT NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "label" TEXT NOT NULL DEFAULT 'Primary',
  "apiKey" TEXT,
  CONSTRAINT "AiProviderConfig_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "JobRun" (
  "id" TEXT NOT NULL,
  "jobType" TEXT NOT NULL,
  "status" "JobStatus" NOT NULL DEFAULT 'QUEUED',
  "startedAt" TIMESTAMP(3),
  "finishedAt" TIMESTAMP(3),
  "attempt" INTEGER NOT NULL DEFAULT 1,
  "message" TEXT,
  "metadataJson" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "triggerSource" TEXT,
  "aiProvider" TEXT,
  "aiModel" TEXT,
  "reportSlug" TEXT,
  "promptTokens" INTEGER,
  "completionTokens" INTEGER,
  "totalTokens" INTEGER,
  CONSTRAINT "JobRun_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ManualEditLog" (
  "id" TEXT NOT NULL,
  "reportId" TEXT NOT NULL,
  "editorLabel" TEXT NOT NULL,
  "note" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ManualEditLog_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ReportFeedback" (
  "id" TEXT NOT NULL,
  "reportId" TEXT NOT NULL,
  "reaction" "FeedbackReaction" NOT NULL,
  "reason" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ReportFeedback_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ReportPageView" (
  "id" TEXT NOT NULL,
  "reportId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ReportPageView_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "AdminUser" (
  "id" TEXT NOT NULL,
  "username" TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "AutomationSetting" (
  "id" TEXT NOT NULL,
  "jobType" TEXT NOT NULL,
  "scheduleHourEt" INTEGER NOT NULL,
  "scheduleMinuteEt" INTEGER NOT NULL,
  "lastScheduledDateEt" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "AutomationSetting_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "AiProviderConfig"
  ADD COLUMN IF NOT EXISTS "label" TEXT NOT NULL DEFAULT 'Primary',
  ADD COLUMN IF NOT EXISTS "apiKey" TEXT;

ALTER TABLE "JobRun"
  ADD COLUMN IF NOT EXISTS "triggerSource" TEXT,
  ADD COLUMN IF NOT EXISTS "aiProvider" TEXT,
  ADD COLUMN IF NOT EXISTS "aiModel" TEXT,
  ADD COLUMN IF NOT EXISTS "reportSlug" TEXT,
  ADD COLUMN IF NOT EXISTS "promptTokens" INTEGER,
  ADD COLUMN IF NOT EXISTS "completionTokens" INTEGER,
  ADD COLUMN IF NOT EXISTS "totalTokens" INTEGER;

CREATE UNIQUE INDEX IF NOT EXISTS "NewsSource_slug_key" ON "NewsSource"("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "RawNewsItem_url_key" ON "RawNewsItem"("url");
CREATE INDEX IF NOT EXISTS "RawNewsItem_sourceId_publishedAt_idx" ON "RawNewsItem"("sourceId", "publishedAt");
CREATE UNIQUE INDEX IF NOT EXISTS "NewsEvent_slug_key" ON "NewsEvent"("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "NewsEventSource_eventId_rawNewsItemId_key" ON "NewsEventSource"("eventId", "rawNewsItemId");
CREATE UNIQUE INDEX IF NOT EXISTS "DailyReport_slug_key" ON "DailyReport"("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "DailyReport_marketDate_key" ON "DailyReport"("marketDate");
CREATE UNIQUE INDEX IF NOT EXISTS "DailyReportEvent_reportId_eventId_key" ON "DailyReportEvent"("reportId", "eventId");
CREATE INDEX IF NOT EXISTS "DailyReportEvent_reportId_sortOrder_idx" ON "DailyReportEvent"("reportId", "sortOrder");
CREATE INDEX IF NOT EXISTS "StockFocus_symbol_idx" ON "StockFocus"("symbol");
CREATE INDEX IF NOT EXISTS "JobRun_jobType_createdAt_idx" ON "JobRun"("jobType", "createdAt");
CREATE INDEX IF NOT EXISTS "ManualEditLog_reportId_createdAt_idx" ON "ManualEditLog"("reportId", "createdAt");
CREATE INDEX IF NOT EXISTS "ReportFeedback_reportId_createdAt_idx" ON "ReportFeedback"("reportId", "createdAt");
CREATE INDEX IF NOT EXISTS "ReportFeedback_reportId_reaction_idx" ON "ReportFeedback"("reportId", "reaction");
CREATE INDEX IF NOT EXISTS "ReportPageView_reportId_createdAt_idx" ON "ReportPageView"("reportId", "createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "AdminUser_username_key" ON "AdminUser"("username");
CREATE UNIQUE INDEX IF NOT EXISTS "AutomationSetting_jobType_key" ON "AutomationSetting"("jobType");

DO $$
BEGIN
  ALTER TABLE "RawNewsItem"
    ADD CONSTRAINT "RawNewsItem_sourceId_fkey"
    FOREIGN KEY ("sourceId") REFERENCES "NewsSource"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "NewsEventSource"
    ADD CONSTRAINT "NewsEventSource_eventId_fkey"
    FOREIGN KEY ("eventId") REFERENCES "NewsEvent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "NewsEventSource"
    ADD CONSTRAINT "NewsEventSource_rawNewsItemId_fkey"
    FOREIGN KEY ("rawNewsItemId") REFERENCES "RawNewsItem"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "DailyReportEvent"
    ADD CONSTRAINT "DailyReportEvent_reportId_fkey"
    FOREIGN KEY ("reportId") REFERENCES "DailyReport"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "DailyReportEvent"
    ADD CONSTRAINT "DailyReportEvent_eventId_fkey"
    FOREIGN KEY ("eventId") REFERENCES "NewsEvent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "StockFocus"
    ADD CONSTRAINT "StockFocus_reportId_fkey"
    FOREIGN KEY ("reportId") REFERENCES "DailyReport"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "ManualEditLog"
    ADD CONSTRAINT "ManualEditLog_reportId_fkey"
    FOREIGN KEY ("reportId") REFERENCES "DailyReport"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "ReportFeedback"
    ADD CONSTRAINT "ReportFeedback_reportId_fkey"
    FOREIGN KEY ("reportId") REFERENCES "DailyReport"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "ReportPageView"
    ADD CONSTRAINT "ReportPageView_reportId_fkey"
    FOREIGN KEY ("reportId") REFERENCES "DailyReport"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

COMMIT;
